language: csharp
mono: none
dotnet: 3.1.201
script:
 - dotnet publish -c Release WebAppHosted.Client/WebAppHosted.Client.csproj
 - touch WebAppHosted.Client/bin/Release/netstandard2.1/publish/wwwroot/.nojekyll
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: WebAppHosted.Client/bin/Release/netstandard2.1/publish/wwwroot
  repo: feruxmax/feruxmax.github.io
  target_branch: master
  on:
    branch: master 
