name: Main
 
env:
  CLIENT_PROJECT: WebAppHosted.Client/WebAppHosted.Client.csproj
  INDEX_HTML: WebAppHosted.Client/wwwroot/index.html
  PUBLISH_DIR: WebAppHosted.Client/bin/Release/net5.0/publish/wwwroot
  
on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '5.0.100-rc.2.20479.15'
          
      -
        uses: actions/checkout@v2
        
      -
        name: Rewrite base 
        run: sed -i 's#<base href="/"#<base href="/ties/"#' ${{env.INDEX_HTML}}
        
      - 
        name: Publish
        run: dotnet publish -c Release ${{ env.CLIENT_PROJECT }}

      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
